### ISSUE TITLE
Issue with 6 encoder layer checkpoint download link

### ISSUE THREAD

**Issue by gluver** [ChuXiaokai/WSDMCUP_BaiduPLM_Paddle#12]
Hi, the current checkpoint file pointed by  [baidu_ultr_paddle_6l_12h_768e](https://drive.google.com/file/d/1tcQ-_VkKbV4ESE2Wu9FgAx9wVvO6Fc7w/view?usp=sharing) in Readme.md is actually same as the 3 encoder layers' checkpoint, perhaps it should be synced as the one in the [ultr_dataset repo](https://github.com/ChuXiaokai/baidu_ultr_dataset.git) ? 

The link of 6L checkpoint in another repo:
https://drive.google.com/file/d/1MBGfCDH7giODsnfThtotIfpM6KI_szFw/view

**Comment by zoulixin93** [comment]
The correct link is https://drive.google.com/file/d/1EiBdWg6V_nOoX2CJMw2nD8_2_N1H2lDa/view?usp=share_link. We will update the github.
