### ISSUE TITLE
结果格式异常：list index out of range

### ISSUE THREAD

**Issue by sunxiaojie99** [ChuXiaokai/WSDMCUP_BaiduPLM_Paddle#15]
![image](https://user-images.githubusercontent.com/41667783/209127089-a272b923-c1b8-40bc-af82-cebb309f1522.png)
可以帮忙看看为什么提交的结果文件异常吗，仔细比对了下官方的格式没有什么问题，也是直接按照官方给的submit.py代码生成的

**Comment by zoulixin93** [comment]
注意更换到第二阶段的测试集
